version: "3.9"
services:
  todo-api:
    container_name: todo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:5.0.11
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db